=== zhcase/lerna-imooc-java/out/production/imooc/plan.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT teaching-plan (course*)>
<!ELEMENT course (course-name,class-hour,exam-form)>
<!ELEMENT  course-name (#PCDATA)>
<!ELEMENT  class-hour (#PCDATA)>
<!ELEMENT  exam-form (#PCDATA)>

=== zhcase/lerna-imooc-java/02/imooc-two-lesson10-11-xml/src/plan.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE teaching-plan SYSTEM "plan.dtd">
<teaching-plan>
    <course>
        <course-name>大学英语</course-name>
        <class-hour>36</class-hour>
        <exam-form>考试</exam-form>
    </course>
    <course>
        <course-name>高等数学</course-name>
        <class-hour>70</class-hour>
        <exam-form>考试</exam-form>
    </course>
    <course>
        <course-name>计算机应用基础</course-name>
        <class-hour>108</class-hour>
        <exam-form>上机考试</exam-form>
    </course>
</teaching-plan>
